POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRpZWdvIiwiaWQiOiI2MWFiNTZhOWMwODZhNzRjOWM1OTM4MDQiLCJpYXQiOjE2Mzg5NzYyMzJ9.7wigWMoJXzA9hODqolWi_yunfaF4ethHw0VcovCppqI

{
    "content": "TEST Diego TOKEN",
    "important": true,
    "userId": "61ab569ec086a74c9c593800"
}